### PR TITLE
First official release 

### PR DESCRIPTION
**Pull request by notthetup**
We have been using `jhwbus` internally for a while and it is stable enough. Should do a first official merge to `master` and a release?

It would be great if this would be published as a Github package. However, we'll have to carefully build the jar to contain the native library for all the supported platforms.

- x86_64.dylib
- aarch64.dylib
- aarch64.so
- armv7l.so
- x86_64.so

### CODE REVIEW

**Review by mchitre — APPROVED** [review]
Looks good.

For bundling, could we use CI with different architectures? Or do we do it manually and check in the binary?

**Comment by notthetup** [comment]
Building with CI should be possible, but we'll have to generate separate jars on different `platforms`, publish them to the release area, and then merge them.

**Comment by notthetup** [comment]
Looked into this, it seems that building on ARM might be more involved. Github Actions don't support ARM based platforms by default. We'll have to use some external service to run a self hosted Github Actions runner.

**Comment by mchitre** [comment]
@notthetup To be merged?

**Comment by notthetup** [comment]
I guess we can merge it. But we'll have for the release, we'll have to manually create a jar that would work across the various platforms.

**Comment by mchitre** [comment]
I don't see us changing this very often, so I guess a manual process once in a blue moon is OK. We should just document the process, so we can blindly follow it.

**Pull request merged**
